tournament/quiz/urls.py
from django.urls import path
from rest_framework import routers
from . import views
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views

router = routers.DefaultRouter()
router.register("api/tournament",views.TournamentViewset,"TournamentViewset")

urlpatterns = [
    url(r'^login/', auth_views.LoginView.as_view(template_name="quiz/registration/login.html"), name="login"),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page="login"), name='logout'),
    path('signup', views.signup, name='signup'),

    path('', views.dashboard, name='dashboard'),
    path('tournaments', views.tournaments, name='tournaments'),
    path('quiz/<int:id>/', views.quiz, name='quiz'),
    path('results/<int:id>/', views.results, name='results'),
]

urlpatterns += router.urls

tournament/tournament/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz.urls')),
]

tournament/quiz/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.db.models import Max, Avg
from datetime import date
import json

class Category(models.Model):
    category = models.CharField(max_length=50)
    key = models.IntegerField()

    def __str__(self):
        return self.category

class User(AbstractUser):
  interests = models.ManyToManyField(Category, blank=True, related_name='interested_players')

  @property
  def taken(self):
      return UserTournament.objects.filter(user_id = self.id)

class Tournament(models.Model):
    DIFFICULTY_CHOICES = [
    ('easy', 'Easy'),
    ('medium', 'Medium'),
    ('hard', 'Hard'),
    ]

    name = models.CharField(max_length=50)
    difficulty = models.CharField(max_length=6, choices=DIFFICULTY_CHOICES)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    questions = models.TextField()

    @property
    def total_taken(self):
        return len(UserTournament.objects.filter(tournament_id=self.id))
    
    @property
    def quiz_questions(self):
        return json.dumps([q['question'] for q in json.loads(self.questions)])
    
    @property
    def taken_by(self):
        return [t.user_id for t in self.tournaments.all()]

    @property
    def high_score(self):
        max = UserTournament.objects.filter(tournament_id=self.id).aggregate(Max('score'))
        return max["score__max"] if max else 0 

    @property
    def average_score(self):
        average = UserTournament.objects.filter(tournament_id=self.id).aggregate(Avg('score'))
        return average['score__avg']

    @property
    def top_players(self):
        return json.dumps([{"player":t.user.username,"score":t.score,"date":t.date_taken.strftime("%b %d %Y")} for t in UserTournament.objects.filter(tournament_id=self.id).order_by('-score')[:5]])

    @staticmethod
    def ongoing():
        return Tournament.objects.filter(start_date__lte=date.today(), end_date__gte=date.today())

    @staticmethod
    def upcoming():
        return Tournament.objects.filter(start_date__gt=date.today())

    @staticmethod
    def past():
        return Tournament.objects.filter(end_date__lt=date.today())

class UserTournament(models.Model):
    user = models.ForeignKey(User,related_name="players", on_delete=models.CASCADE)
    tournament = models.ForeignKey(Tournament,related_name="tournaments", on_delete=models.CASCADE)
    score = models.IntegerField(default=0)
    date_taken = models.DateTimeField(auto_now_add=True)
    answers = models.TextField()

tournament/quiz/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from .models import Category, User

class SignUpForm(UserCreationForm):
    interests = forms.ModelMultipleChoiceField(
    queryset=Category.objects.all(),
    widget=forms.CheckboxSelectMultiple,
    required=True
)
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'interests')

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.save()
        user.interests.add(*self.cleaned_data.get('interests'))
        return user
    

tournament/quiz/views.py
from django.shortcuts import get_object_or_404, render,redirect
from django.http import HttpResponse, JsonResponse

from rest_framework import viewsets

from  .models import Tournament,Category,UserTournament,User
from .serializer import TournamentSerializer
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from .forms import SignUpForm
from django.views.generic import CreateView
from django.core import serializers
import json
import random

# user signup
def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('/tournaments')
    else:
        form = SignUpForm()
    return render(request, 'quiz/signup_form.html', {'form': form})

# user dashboard
@login_required(login_url='/login/')
def dashboard(request):
    return render(request, 'quiz/dashboard.html', {'tournament_ongoing': Tournament.ongoing(), 'tournament_upcoming': Tournament.upcoming(), 'tournament_past': Tournament.past(), 'average_score': Tournament.average_score})

# questions
def quiz(request, id):
    tournament = Tournament.objects.get(id = id)
    questions = json.loads(tournament.questions)
    for question in questions:
        question['incorrect_answers'].append(question['correct_answer'])
        random.shuffle(question['incorrect_answers'])
    return render(request, 'quiz/quiz.html', {'tournament': tournament,"questions":questions})    

# results
def results(request, id):
    tournament = Tournament.objects.get(id = id)
    questions = json.loads(tournament.questions)
    results = UserTournament.objects.filter(tournament_id=id,user_id=request.user.id)
    if request.method == "POST" and not results:
        total = 0
        for i in range(1,10):
            user_answer = request.POST.get(str(i), None)
            if user_answer == questions[i-1]['correct_answer']:
                total += 1
            questions[i-1]["user_answer"] = user_answer
        results = UserTournament.objects.create(tournament_id=id,user_id=request.user.id,score=total,answers=json.dumps(questions))
        return redirect(f'/results/{id}')
    else:
        answers = []
        if results:
            results = results[0]
            answers = json.loads(results.answers)
        return render(request, 'quiz/results.html',{"results":results,"answers":answers})    

# tournaments and categories
def tournaments(request):
    tournaments = Tournament.objects.all()
    categories = Category.objects.all()
    return render(request, 'quiz/tournaments.html', {'tournaments':tournaments, 'categories':categories})	


class TournamentViewset(viewsets.ModelViewSet):
    serializer_class = TournamentSerializer
    def get_queryset(self):
        return Tournament.objects.all()

    def perform_create(self, serializer):
        serializer.save()

tournament/quiz/templates/quiz/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark capitalise">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if page == 'dashboard' %} active {% endif %}">
                    <a class="nav-link" href="/">Home<span class="sr-only">(current)</span></a>
                </li>
                {% if user.is_authenticated and user.is_staff %}
                <li class="nav-item {% if page == 'data' %} active {% endif %}">
                    <a class="nav-link" href="/tournaments" id="tournaments">Tournaments</a>
                </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.username }}</a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                  </div>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="/login">Login</a>
                  </li>
            {% endif %}
              </ul>

        </div>
    </nav>
    <div class="mt-3"></div>

    <div class="page-header text-center">
        <h1>Quiz tournament</h1>
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-12">
                {% block content %}

                {% endblock %}
            </div>
        </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/script.js' %}"></script>

</body>

</html>

tournament/quiz/templates/quiz/dashboard.html
{% extends 'quiz/base.html' %}

{% block content %}

<div>
    <h3>Dashboard</h3>
    <!-- Nav tabs -->
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#Ongoing">Ongoing</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#Upcoming">Upcoming</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#Past">Past</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#Taken">Taken</a>
        </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div class="tab-pane container active" id="Ongoing">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Category</th>
                        <th scope="col">Difficulty</th>
                        <th scope="col">Start Date</th>
                        <th scope="col">End Date</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for tournament  in tournament_ongoing %}
                    {% if user.id not in tournament.taken_by %}
                    <tr>
                        <td>{{ tournament.name }}</td>
                        <td>{{ tournament.category }}</td>
                        <td>{{ tournament.get_difficulty_display }}</td>
                        <td>{{ tournament.start_date }}</td>
                        <td>{{ tournament.end_date }}</td>
                        {% if user.is_authenticated %}
                        <td>
                            <a href="/quiz/{{ tournament.id }}" role="button" class="btn btn-sm btn-warning">Play
                                game</a>
                        </td>
                        {% endif %}
                    </tr>
                    {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="tab-pane container fade" id="Upcoming">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Sl.No</th>
                        <th scope="col">Name</th>
                        <th scope="col">Category</th>
                        <th scope="col">Difficulty</th>
                        <th scope="col">Start Date</th>
                        <th scope="col">End Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for tournament  in tournament_upcoming %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ tournament.name }}</td>
                        <td>{{ tournament.category }}</td>
                        <td>{{ tournament.get_difficulty_display }}</td>
                        <td>{{ tournament.start_date }}</td>
                        <td>{{ tournament.end_date }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="tab-pane container fade" id="Past">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Sl.No</th>
                        <th scope="col">Name</th>
                        <th scope="col">Category</th>
                        <th scope="col">Difficulty</th>
                        <th scope="col">Start Date</th>
                        <th scope="col">End Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for tournament  in tournament_past %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ tournament.name }}</td>
                        <td>{{ tournament.category }}</td>
                        <td>{{ tournament.get_difficulty_display }}</td>
                        <td>{{ tournament.start_date }}</td>
                        <td>{{ tournament.end_date }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="tab-pane container fade" id="Taken">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Sl.No</th>
                        <th scope="col">Name</th>
                        <th scope="col">Category</th>
                        <th scope="col">Difficulty</th>
                        <th scope="col">Your Score</th>
                        <th scope="col">Average Score</th>
                        <th scope="col">Total Taken</th>
                        <th scope="col">Highest scores</th>
                        <th scope="col">Results</th>
                    </tr>
                </thead>
                <tbody>
                    {% for taken  in user.taken %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ taken.tournament.name }}</td>
                        <td>{{ taken.tournament.category }}</td>
                        <td>{{ taken.tournament.get_difficulty_display }}</td>
                        <td>{{ taken.score }} / 10</td>
                        <td>{{ taken.tournament.average_score }}</td>
                        <td>{{ taken.tournament.total_taken }}</td>
                        <td>
                            <button type="button" data-players="{{taken.tournament.top_players}}" class="btn btn-sm btn-info viewScores">Highscore</button>
                        </td>
                        <td>
                            <a href="/results/{{ taken.tournament.id }}" role="button" class="btn btn-sm btn-info">Results</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="modal fade" id="scoreModal" tabindex="-1" role="dialog" aria-labelledby="scoreModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="scoreModalLabel">View Scores</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>User Name</th>
                            <th>Highest Score</th>
                            <th>Date Participated</th>
                        </tr>
                    </thead>
                    <tbody id="topPlayerBody">
                       
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}

tournament/quiz/templates/quiz/quiz.html
{% extends 'quiz/base.html' %}

{% block content %}

<div class="container p-5">
    <h3>{{ tournament.name }} <small class="text-info">({{ tournament.category.category }})</small></h3>
    <form method="post" action="/results/{{tournament.id}}/">
        {% csrf_token %}
        <div>
            {% for question in  questions  %}
            {% with outer_loop=forloop.counter %}
                <label style="font-weight: bold;">{{forloop.counter}}.{{ question.question |safe}}</label>
                {% for ans in  question.incorrect_answers  %}
                <div class="form-check ml-3">
                <label class="form-check-label">
                <input class="form-check-input" type="radio" name="{{ outer_loop }}" value="{{ans|safe}}">{{ans|safe}}
                </label>
                </div>
                {% endfor %}
            {% endwith %}
            {% endfor %}
        </div>
        <div>
            <input class="btn btn-primary offset-md-5" type="submit" value="Submit">
        </div>
    </form>
</div>

{% endblock %}

tournament/quiz/templates/quiz/results.html
{% extends 'quiz/base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md">
            <div class="card text-white bg-primary mb-3">
                <div class="card-header">Tournament</div>
                <div class="card-body">
                    <h5 class="card-title">{{ results.tournament.name }}</h5>
                    <p class="card-text"></p>
                </div>
            </div>
        </div>
        <div class="col-md">
            <div class="card text-white bg-success mb-3">
                <div class="card-header">Your score</div>
                <div class="card-body">
                    <h5 class="card-title">{{ results.score }} / 10</h5>
                    <p class="card-text"></p>
                </div>
            </div>
        </div>
        <div class="col-md">
            <div class="card text-white bg-secondary mb-3">
                <div class="card-header">Total participants</div>
                <div class="card-body">
                    <h5 class="card-title">{{ results.tournament.total_taken }}</h5>
                    <p class="card-text"></p>
                </div>
            </div>
        </div>
        <div class="col-md">
            <div class="card text-white bg-danger mb-3">
                <div class="card-header">Highest score</div>
                <div class="card-body">
                    <h5 class="card-title">{{ results.tournament.high_score }}</h5>
                    <p class="card-text"></p>
                </div>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-header bg-info text-white">
            Results
        </div>
        <div class="card-body">
            {% for question in answers %}
            <h5>{{ forloop.counter }} . {{ question.question |safe}}
                {% if question.correct_answer == question.user_answer  %}
                <small class="badge badge-pill badge-success">Correct</small>
                {% else %}
                <small class="badge badge-pill badge-danger">Wrong</small>
                {% endif %}
            </h5>
            <ul>
                <li><span class="text-info">Answer : {{question.correct_answer|safe}}</span></li>
                {% if question.correct_answer != question.user_answer  %}
                <li><span class="text-danger">Your answer : {% if question.user_answer  %}  {{question.user_answer | safe}} {% else %} Not answered {% endif %}</span></li>
                {% endif %}
            </ul>
            {% endfor %}
        </div>
    </div>

</div>
{% endblock %}

tournament/quiz/templates/quiz/signup_form.html
{% extends 'quiz/base.html' %}

{% block content %}

<div class="container p-5">
    <div>
      <form method="post" novalidate>
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {{ form.as_p }}
        <button type="submit" class="btn btn-success float-center" id="signup">Sign Up</button>
      </form>
    </div>
</div>

{% endblock %}

tournament/quiz/templates/quiz/tournaments.html
{% extends 'quiz/base.html' %}

{% block content %}

<div>
    {% if user.is_authenticated and user.is_staff %}
        <button type="button" class="btn btn-info addTournament" id="newTournament">New Tournament</button>
    {% endif %}
    {% if not user.is_authenticated %}
        <span class="text-center text-danger">Login to play quiz</span>
    {% endif %}
    <table class="table table-striped">
        <thead class="text-center">
            <tr>
                <th scope="col">Sl.No</th>
                <th scope="col">Name</th>
                <th scope="col">Category</th>
                <th scope="col">Difficulty</th>
                <th scope="col">Start Date</th>
                <th scope="col">End Date</th>
                <th scope="col">Taken</th>
                {% if user.is_authenticated %}
                <th scope="col">Action</th>
                {% endif %}
            </tr>
        </thead>
        <tbody class="text-center">
            {% for tournament in tournaments %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ tournament.name }}</td>
                <td>{{ tournament.category }}</td>
                <td>{{ tournament.get_difficulty_display }}</td>
                <td>{{ tournament.start_date }}</td>
                <td>{{ tournament.end_date }}</td>
                <td>{{tournament.total_taken}}</td>
                {% if user.is_authenticated and user.is_staff %}
                <td>
                    <button type="button" data-questions="{{tournament.quiz_questions}}" class="btn btn-sm btn-info showQuestions" >View Questions</button>
                    <a href="#" role="button" class="btn btn-sm btn-danger deleteTournament"
                        data-name="{{ tournament.name }}" data-id="{{ tournament.id }}">Delete</a>
                </td>
                {% else %}
                {% if user.id in tournament.taken_by %}</td>
                <td>
                    <a href="/results/{{ tournament.id }}" role="button" class="btn btn-sm btn-info">View result</a>
                </td>
                {% else %}
                {% if user.is_authenticated %}
                <td>
                    <a href="/quiz/{{ tournament.id }}" role="button" class="btn btn-sm btn-warning">Play game</a>
                </td>
                {% endif %}
                {% endif %}
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div class="modal fade" id="tournamentModal" tabindex="-1" role="dialog" aria-labelledby="tournamentModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="tournamentModalLabel">Add Tournament</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="tournamentForm">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" class="form-control" id="name" name="name" placeholder="Name">
                    </div>

                    <div class="form-group">
                        <label for="category">Category</label>
                        <select class="form-control" id="category" name="category_id">
                            {% for category in categories %}
                            <option value="{{ category.id }}">{{ category }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="category">Difficulty</label>
                        <select class="form-control" id="difficulty" name="difficulty">
                            <option value="easy">Easy</option>
                            <option value="medium">Medium</option>
                            <option value="hard">Hard</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="start_date">Start Date</label>
                        <input type="date" class="form-control" id="start_date" name="start_date"
                            placeholder="Start date">
                    </div>
                    <div class="form-group">
                        <label for="end_date">End Date</label>
                        <input type="date" class="form-control" id="end_date" name="end_date" placeholder="End date">
                    </div>

                    <label class="text-danger" id="dateValid"></label>

                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-info tournamentSubmit" id="save">Save</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="questionsModal" tabindex="-1" role="dialog" aria-labelledby="questionsModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="questionsModalLabel">View Questions</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="questionsBody">

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}